import { NextResponse } from 'next/server';
import {
    getAllCampaigns,
    createCampaign,
} from '@/lib/database';
import { getDefaultConfig } from '@/lib/scoring';
import { applyRateLimit, RATE_LIMIT_CONFIGS } from '@/lib/rate-limit';
import type { Campaign } from '@/lib/types';

/**
 * GET /api/campaigns
 * List all campaigns
 */
export async function GET() {
    try {
        const campaigns = await getAllCampaigns();
        return NextResponse.json({
            success: true,
            data: campaigns,
        });
    } catch (error) {
        console.error('Error fetching campaigns:', error);
        return NextResponse.json(
            { success: false, error: 'Failed to fetch campaigns' },
            { status: 500 }
        );
    }
}

/**
 * POST /api/campaigns
 * Create a new campaign
 */
export async function POST(request: Request) {
    // Apply rate limiting
    const rateLimitResponse = applyRateLimit(request, RATE_LIMIT_CONFIGS.createCampaign);
    if (rateLimitResponse) return rateLimitResponse;

    try {
        const body = await request.json();

        // Validation
        if (!body.name) {
            return NextResponse.json(
                { success: false, error: 'Campaign name is required' },
                { status: 400 }
            );
        }

        const campaignData: Omit<Campaign, 'id' | 'createdAt' | 'updatedAt'> = {
            name: body.name,
            description: body.description || '',
            status: body.status || 'draft',

            // SaaS fields (ADDED)
            slug: '', // Will be generated by createCampaign
            method: body.method || 'mirror',
            trafficSource: body.trafficSource || 'general',
            trackClicks: body.trackClicks !== undefined ? body.trackClicks : true,

            safePageUrl: body.safePageUrl,
            safePageHtml: body.safePageHtml,
            realPageUrl: body.realPageUrl,
            realPageHtml: body.realPageHtml,
            config: body.config || getDefaultConfig(),
        };

        const campaign = await createCampaign(campaignData);

        return NextResponse.json({
            success: true,
            data: campaign,
            message: 'Campaign created successfully',
        });
    } catch (error) {
        console.error('Error creating campaign:', error);
        return NextResponse.json(
            { success: false, error: 'Failed to create campaign' },
            { status: 500 }
        );
    }
}
